-- RANGOS
insert into RANGO (ID, VERSION, PUNTAJE_MAXIMO, DESCRIPCION) values (1, 0, 1000, 'Sin Rango')
insert into RANGO (ID, VERSION, PUNTAJE_MAXIMO, DESCRIPCION) values (2, 0, 25000, 'Trainee')

-- VER SI SON NECESARIOS PARA LAS HISTORIAS DE USUARIO SOLICITADAS
insert into RANGO (ID, VERSION, PUNTAJE_MAXIMO, DESCRIPCION) values (3, 0, 100000, 'Junior')
insert into RANGO (ID, VERSION, PUNTAJE_MAXIMO, DESCRIPCION) values (4, 0, 500000, 'Semi Senior')
insert into RANGO (ID, VERSION, PUNTAJE_MAXIMO, DESCRIPCION) values (5, 0, 1000000, 'Senior')

-- DESARROLLADOR (INICIALIZADO CON 400 PUNTOS DE INVESTIGACION PARA HISTORIA DE USUARIO SOLICITADA)
insert into DESARROLLADOR (ID, VERSION, RANGO_ID, PUNTOS_INVESTIGACION) values (1, 0, 1, 400)

-- PROYECTO
insert into PROYECTO (ID, VERSION, DESCRIPCION) values (1, 0, 'The Tales of Lezda')

-- DESARROLLO (ESTOY AGREGANDO CAMPOS DESRCIPCION Y EXPLICACION)
insert into DESARROLLO (ID, VERSION, PROYECTO_ID, PUNTAJE_OTORGADO, NRO_ORDEN, NOMBRE, DESCRIPCION) values (1, 0, 1, 200, 1, 'Saltar Obstáculo', 'Agregar acá un texto que explique lo que se tiene que desarrollar.')

-- INVESTIGACION PARECE NO SER NECESARIO